
version: '3.6'
services:
  grafana:
    image: alansup/mvision:1.0
    restart: always
    ports:
      - 3000:3000
    container_name: grafana
    environment:
      - TZ=Europe/Berlin
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    volumes:
      - ./configFile/grafana.ini:/etc/grafana/grafana.ini:ro
    depends_on:
      - renderer

  renderer:
    image: grafana/grafana-image-renderer:3.5.0
    container_name: grafana_renderer
    ports:
      - 8081
    environment:
      ENABLE_METRICS: 'true'

volumes:
  grafana_data: {}
  influxdb_data: {}


