
version: '3.6'
services:
  telegraf:
    image: telegraf:1.22.4
    container_name: $ip-Monitor-$num-Telegraf
    restart: always
    volumes:
      - ./configFile/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    ports:
      - '$telegraf:8125'

  influxdb:
    image: influxdb:1.8.10
    container_name: $ip-Monitor-$num-Influxdb
    restart: always
    ports:
      - '$influx:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  grafana_data: {}
  influxdb_data: {}
